import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Proposal AI', // Changed title here
  description: 'Generate professional proposals with AI assistance.', // Updated description
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* The <title> tag is usually automatically generated by Next.js from the metadata export */}
        {/* If you had a direct <title> tag here, you would change it as well */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
